#!/usr/bin/env bash
# Copyright 2026 Ferrite Engineering LLC
# SPDX-License-Identifier: Apache-2.0

# Regenerates examples/getting-started/report.sarif from the real engines.
#
# The report is committed so that somebody with NO lint engine installed
# can still open LintCrux and see a real report — File → Import SARIF
# report…. It is therefore the one artifact in examples/ that a reader
# cannot reproduce without a toolchain, which is exactly why it must be
# regenerated by a script rather than edited.
#
# Step 2 is not cosmetic. `--sarif` writes `originalUriBaseIds` as an
# absolute `file://` URI — the author's home directory. Committing that
# leaks a path and makes the file machine-specific. The result URIs
# themselves are already relative to %SRCROOT% (`alu.sv`), so rebasing the
# declaration onto the SARIF file's own directory loses nothing and makes
# the report portable.
#
# Run from the lintcrux package root:
#   ./tool/regen_example_report.sh
set -euo pipefail

cd "$(dirname "$0")/.."

OUT=examples/getting-started/report.sarif

echo "1/2 running the real engines"
dart run bin/lintcrux.dart examples/getting-started/project.lintcrux --sarif "$OUT"

echo "2/2 rebasing %SRCROOT% off the capture host"
python3 - "$OUT" <<'PY'
import json, sys

path = sys.argv[1]
with open(path) as f:
    doc = json.load(f)

for run in doc.get('runs', []):
    bases = run.get('originalUriBaseIds')
    if bases:
        for key in bases:
            # Relative to the directory holding this SARIF file, which is
            # the project root for a committed example.
            bases[key] = {'uri': './'}

with open(path, 'w') as f:
    json.dump(doc, f, indent=2)
    f.write('\n')
PY

echo "wrote $OUT"
