// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

/// App-launch CLI flags — the suite-shared `--reset` / `--no-restore`
/// contract, ported from WaveCrux's `services/cli/cli_args.dart`.
///
/// LintCrux's *primary* CLI surface (positional paths, `--export`,
/// `--engine`, `--workspace`, `--help`, …) is owned by [`CliArgsParser`]
/// (`core/cli/cli_args_parser.dart`), a strict `package:args` parser shared
/// with the headless `bin/lintcrux.dart` binary — where an unknown flag is
/// a usage error by design (CI exit code 64). The launch recovery flags
/// live here instead: `bootstrap()` parses them first and strips them from
/// the argument list before the strict parser runs, so they never trip
/// that error path. Tests build a [CliArgs] directly to exercise startup
/// behavior without touching `Platform.executableArguments`.
library;

/// Parsed result of app-launch flag parsing.
///
/// Pure-data structure consumed by `bootstrap()` to decide whether to clear
/// persisted state ([reset]) and/or skip this launch's workspace restore
/// ([noRestore]).
class CliArgs {
  /// Creates a parsed flag set; defaults describe a normal launch.
  const CliArgs({
    this.reset = false,
    this.noRestore = false,
  });

  /// `--reset` flag — clear all persisted restore state (the auto-managed
  /// `workspace.json` and every per-tab session sidecar) before launching
  /// into a fresh, empty workspace. The recovery escape hatch for a session
  /// so corrupt it wedges startup. Destructive but scoped: it does NOT touch
  /// app settings, the keymap, or recent-files history.
  final bool reset;

  /// `--no-restore` flag — skip restoring the previous session's tabs for
  /// this launch only, without deleting anything. The workspace document is
  /// left untouched on disk, so the next normal launch (or re-enabling the
  /// Settings toggle) brings the session back. The non-destructive first
  /// thing to try when the app hangs on startup: if it launches cleanly, the
  /// previous session was the culprit and `--reset` clears it permanently.
  final bool noRestore;
}

/// Parses [args] into a [CliArgs] structure.
///
/// Only `--reset` and `--no-restore` are recognized here; every other
/// argument is left for [`CliArgsParser`] and silently ignored by this
/// parser — a launch-recovery flag must never be the thing that wedges
/// startup.
CliArgs parseCliArgs(List<String> args) {
  var reset = false;
  var noRestore = false;
  for (final a in args) {
    if (a == '--reset') {
      reset = true;
    } else if (a == '--no-restore') {
      noRestore = true;
    }
  }
  return CliArgs(reset: reset, noRestore: noRestore);
}

/// Returns [args] with the launch flags (`--reset`, `--no-restore`) removed.
///
/// `bootstrap()` feeds the stripped list to the strict [`CliArgsParser`],
/// which would otherwise reject them as unknown flags with a usage error.
List<String> stripLaunchFlags(List<String> args) => List<String>.unmodifiable(
  args.where((a) => a != '--reset' && a != '--no-restore'),
);

/// Supplemental `--help` block for the launch recovery flags.
///
/// LintCrux's primary usage text is generated by `package:args` inside
/// [`CliArgsParser.usage`]; these flags are parsed before that parser runs,
/// so `bootstrap()` appends this block when printing `--help`.
String cliHelpText() => '''
App-launch options (desktop UI only; not honored by the headless binary):
  --no-restore              Launch without reopening the previous
                            session's tabs (nothing is deleted). Try this
                            first if the app hangs on startup.
  --reset                   Clear all saved workspace/session state
                            (workspace document + per-tab sessions) and
                            launch empty. Settings and recent files are
                            kept.
''';
