// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'dart:io';

import 'package:lintcrux/domain/enums/hdl_language.dart';
import 'package:lintcrux/domain/models/project_source_file.dart';
import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// The EDAM version this reader is written against.
///
/// EDAM has a `version:` field but no published compatibility policy —
/// the format is generated by FuseSoC/Edalize and documented nowhere
/// but their source. Anything other than this exact version imports on
/// a best-effort basis with a loud warning rather than a refusal:
/// the fields we consume (`files`, `toplevel`, `parameters`,
/// `tool_options`) have been stable across recent Edalize releases,
/// and a hard version gate would break users on the next harmless
/// point bump.
const String kSupportedEdamVersion = '0.2.1';

/// Reader for FuseSoC/Edalize **EDAM** (`.eda.yml`) files.
///
/// EDAM is the data structure FuseSoC hands to Edalize after compiling
/// a design's CAPI2 `.core` files: every conditional expression
/// evaluated, every dependency resolved and staged on disk, the
/// toplevel a plain string, and every parameter pre-classified with
/// `datatype` / `paramtype`. Running
///
/// ```bash
/// fusesoc run --target=lint --setup vendor:lib:core
/// ```
///
/// leaves one at `build/<name>/<flow>/<name>.eda.yml`, and that file —
/// not the raw `.core` — is the cheapest complete description of a
/// FuseSoC project LintCrux can consume.
///
/// What the reader maps:
///
/// * `files[].name` → source list, resolved against the EDAM's own
///   directory (paths in EDAM are relative to the work root).
/// * `files[].file_type` → per-file language: `verilogSource*` →
///   Verilog, `systemVerilogSource*` → SystemVerilog, `vhdlSource*` →
///   VHDL. `file_type: vlt` is a Verilator waiver/config file and is
///   routed to the Verilator engine's `waiverFiles` option — **not**
///   into the source list, where every other engine would choke on it.
/// * `files[].is_include_file` → the file's directory (or its explicit
///   `include_path`) joins [ImportedEdam.includePaths]; the file itself
///   is not passed as a source. Mirrors Edalize's `_add_include_dir`.
/// * `files[].core` → per-file provenance (which FuseSoC core
///   contributed the file), preserved so a violation table can
///   distinguish "your code" from "a dependency".
/// * `toplevel` → top module (already a resolved string in EDAM).
/// * `parameters` with `paramtype: vlogdefine` and a `default` →
///   defines. `vlogparam` defaults become Verilator `-G` options —
///   LintCrux has no engine-neutral parameter channel, and Verilator
///   is the only bundled engine that elaborates with overridden
///   parameters. Everything else (`plusarg`, `cmdlinearg`, `generic`)
///   is simulation-oriented and skipped with a warning.
/// * `tool_options.verilator.verilator_options` → `-W*` entries become
///   the Verilator engine's `warnFlags`; anything else lands in its
///   `extraOptions`. Options for other tools are reported and ignored.
/// * `hooks` / `filters` / `vpi` → ignored, warned about when
///   non-empty — same discipline as the suite's CAPI2 importer.
///
/// Unsupported constructs **warn and continue**; the reader throws
/// [EdamImportException] only when it cannot produce a usable project
/// at all (unreadable file, invalid YAML, zero lintable sources).
class EdamReader {
  /// Creates an [EdamReader].
  const EdamReader();

  /// Reads [edamPath] into an [ImportedEdam].
  ///
  /// Throws [EdamImportException] for I/O errors, YAML that does not
  /// parse, a document that is not a map, or a file set with no
  /// lintable HDL source at all.
  ImportedEdam read(String edamPath) {
    final canonical = p.normalize(p.absolute(edamPath));
    final file = File(canonical);
    if (!file.existsSync()) {
      throw EdamImportException('EDAM file not found: "$canonical"');
    }
    final String content;
    try {
      content = file.readAsStringSync();
    } on FileSystemException catch (e) {
      throw EdamImportException(
        'could not read EDAM file "$canonical": ${e.message}',
      );
    }
    final Object? doc;
    try {
      doc = loadYaml(content);
    } on YamlException catch (e) {
      throw EdamImportException(
        'EDAM file "$canonical" is not valid YAML: ${e.message}',
      );
    }
    if (doc is! Map) {
      throw EdamImportException(
        'EDAM file "$canonical" does not contain a YAML mapping at the '
        'top level',
      );
    }

    final warnings = <String>[];
    final edamDir = p.dirname(canonical);

    final version = doc['version']?.toString();
    if (version != kSupportedEdamVersion) {
      warnings.add(
        'EDAM version "${version ?? '(missing)'}" is not the version this '
        'importer targets ($kSupportedEdamVersion). The EDAM format is '
        'undocumented and unversioned in practice; importing on a '
        'best-effort basis. Verify the resulting project.',
      );
    }

    final name = doc['name'] is String ? doc['name'] as String : null;
    final toplevel = _resolveToplevel(doc['toplevel'], warnings);

    final sourceFiles = <String>[];
    final includePaths = <String>[];
    final languages = <String, ProjectSourceFileLanguage>{};
    final provenance = <String, String>{};
    final waiverFiles = <String>[];

    final files = doc['files'];
    if (files is List) {
      for (final entry in files) {
        if (entry is! Map) {
          warnings.add('skipped a non-mapping entry in "files"');
          continue;
        }
        _readFileEntry(
          entry,
          edamDir: edamDir,
          sourceFiles: sourceFiles,
          includePaths: includePaths,
          languages: languages,
          provenance: provenance,
          waiverFiles: waiverFiles,
          warnings: warnings,
        );
      }
    } else if (files != null) {
      warnings.add('"files" is not a list; no sources imported from it');
    }

    final defines = <String, String>{};
    final verilatorExtraOptions = <String>[];
    _readParameters(
      doc['parameters'],
      defines: defines,
      verilatorExtraOptions: verilatorExtraOptions,
      warnings: warnings,
    );

    List<String>? warnFlags;
    final toolOptions = doc['tool_options'];
    if (toolOptions is Map) {
      for (final entry in toolOptions.entries) {
        final tool = entry.key.toString();
        if (tool == 'verilator') {
          warnFlags = _readVerilatorOptions(
            entry.value,
            verilatorExtraOptions,
            warnings,
          );
        } else {
          warnings.add(
            'tool_options for "$tool" ignored — LintCrux honors only '
            'the verilator namespace today',
          );
        }
      }
    }

    for (final key in const ['hooks', 'filters', 'vpi']) {
      final value = doc[key];
      final nonEmpty =
          (value is Map && value.isNotEmpty) ||
          (value is List && value.isNotEmpty);
      if (nonEmpty) {
        warnings.add('"$key" is not supported by LintCrux and was ignored');
      }
    }

    if (sourceFiles.isEmpty) {
      throw EdamImportException(
        'EDAM file "$canonical" contains no lintable HDL sources '
        '(verilogSource / systemVerilogSource / vhdlSource)',
      );
    }

    return ImportedEdam(
      name: name,
      version: version,
      toplevel: toplevel,
      sourceFiles: List<String>.unmodifiable(sourceFiles),
      includePaths: List<String>.unmodifiable(includePaths),
      defines: Map<String, String>.unmodifiable(defines),
      sourceFileLanguages: Map<String, ProjectSourceFileLanguage>.unmodifiable(
        languages,
      ),
      sourceFileProvenance: Map<String, String>.unmodifiable(provenance),
      language: _projectLanguage(languages.values),
      verilatorWarnFlags: warnFlags == null
          ? null
          : List<String>.unmodifiable(warnFlags),
      verilatorExtraOptions: List<String>.unmodifiable(verilatorExtraOptions),
      verilatorWaiverFiles: List<String>.unmodifiable(waiverFiles),
      warnings: List<String>.unmodifiable(warnings),
    );
  }

  /// EDAM's `toplevel` is a resolved string in every artifact we have
  /// captured, but the Edalize source tolerates a list — take the first
  /// entry and say so rather than failing an otherwise-good import.
  String? _resolveToplevel(Object? raw, List<String> warnings) {
    if (raw is String && raw.isNotEmpty) return raw;
    if (raw is List && raw.isNotEmpty) {
      final first = raw.first;
      if (first is String && first.isNotEmpty) {
        if (raw.length > 1) {
          warnings.add(
            '"toplevel" lists ${raw.length} entries; using the first '
            '("$first")',
          );
        }
        return first;
      }
    }
    return null;
  }

  void _readFileEntry(
    Map<Object?, Object?> entry, {
    required String edamDir,
    required List<String> sourceFiles,
    required List<String> includePaths,
    required Map<String, ProjectSourceFileLanguage> languages,
    required Map<String, String> provenance,
    required List<String> waiverFiles,
    required List<String> warnings,
  }) {
    final rawName = entry['name'];
    if (rawName is! String || rawName.isEmpty) {
      warnings.add('skipped a "files" entry with no "name"');
      return;
    }
    final abs = _resolveAgainst(edamDir, rawName);
    final fileType = entry['file_type']?.toString() ?? '';
    final core = entry['core'];

    // Include files contribute a search directory, not a source —
    // Edalize's `_add_include_dir` semantics: an explicit
    // `include_path` wins, else the file's own directory.
    if (entry['is_include_file'] == true) {
      final rawInclude = entry['include_path'];
      final dir = rawInclude is String && rawInclude.isNotEmpty
          ? _resolveAgainst(edamDir, rawInclude)
          : p.dirname(abs);
      if (!includePaths.contains(dir)) includePaths.add(dir);
      return;
    }

    if (fileType == 'vlt') {
      // A Verilator waiver/config file. It belongs on Verilator's
      // command line and nowhere near the other engines' source lists.
      waiverFiles.add(abs);
      return;
    }

    final language = _languageForFileType(fileType);
    if (language == null) {
      warnings.add(
        'skipped "$rawName": unsupported file_type "$fileType"',
      );
      return;
    }
    sourceFiles.add(abs);
    languages[abs] = language;
    if (core is String && core.isNotEmpty) {
      provenance[abs] = core;
    }
  }

  /// `file_type` → per-file language. EDAM inherits CAPI2's convention
  /// of suffixing standard revisions (`verilogSource-2005`,
  /// `vhdlSource-2008`), so match on the family prefix.
  ProjectSourceFileLanguage? _languageForFileType(String fileType) {
    if (fileType.startsWith('systemVerilogSource')) {
      return ProjectSourceFileLanguage.systemVerilog;
    }
    if (fileType.startsWith('verilogSource')) {
      return ProjectSourceFileLanguage.verilog;
    }
    if (fileType.startsWith('vhdlSource')) {
      return ProjectSourceFileLanguage.vhdl;
    }
    return null;
  }

  /// Project-level language from the per-file set. Verilog +
  /// SystemVerilog collapses to SystemVerilog (a superset for engine
  /// routing purposes); VHDL alongside either is genuinely `mixed`.
  HdlLanguage _projectLanguage(Iterable<ProjectSourceFileLanguage> perFile) {
    final set = perFile.toSet();
    final hasVhdl = set.contains(ProjectSourceFileLanguage.vhdl);
    final hasVerilogFamily =
        set.contains(ProjectSourceFileLanguage.verilog) ||
        set.contains(ProjectSourceFileLanguage.systemVerilog);
    if (hasVhdl && hasVerilogFamily) return HdlLanguage.mixed;
    if (hasVhdl) return HdlLanguage.vhdl;
    if (set.contains(ProjectSourceFileLanguage.systemVerilog)) {
      return HdlLanguage.systemVerilog;
    }
    return HdlLanguage.verilog;
  }

  void _readParameters(
    Object? raw, {
    required Map<String, String> defines,
    required List<String> verilatorExtraOptions,
    required List<String> warnings,
  }) {
    if (raw == null) return;
    if (raw is! Map) {
      warnings.add('"parameters" is not a mapping; ignored');
      return;
    }
    for (final entry in raw.entries) {
      final paramName = entry.key.toString();
      final spec = entry.value;
      if (spec is! Map) {
        warnings.add('parameter "$paramName" has no specification; ignored');
        continue;
      }
      final paramtype = spec['paramtype']?.toString() ?? '';
      // A parameter without a `default` is a pure declaration — FuseSoC
      // emits it so a *user* can pass `--paramName=value`. There is
      // nothing to apply, exactly as Edalize applies nothing.
      final hasDefault = spec.containsKey('default') && spec['default'] != null;
      final value = hasDefault ? _stringifyParamValue(spec['default']) : null;
      switch (paramtype) {
        case 'vlogdefine':
          if (value != null) defines[paramName] = value;
        case 'vlogparam':
          if (value != null) {
            // Verilator's `-G<name>=<value>` — the same spelling
            // Edalize's own Verilator backend uses. Verilator is the
            // only bundled engine with a parameter-override channel,
            // so the default is honored there and reported for the
            // rest.
            verilatorExtraOptions.add('-G$paramName=$value');
            warnings.add(
              'vlogparam "$paramName" default is applied to Verilator '
              'only (-G$paramName=$value); other engines lint with the '
              'RTL default',
            );
          }
        case 'plusarg':
        case 'cmdlinearg':
        case 'generic':
          if (value != null) {
            warnings.add(
              'parameter "$paramName" (paramtype: $paramtype) is not '
              'used for linting; ignored',
            );
          }
        default:
          warnings.add(
            'parameter "$paramName" has unknown paramtype '
            '"$paramtype"; ignored',
          );
      }
    }
  }

  /// Renders a parameter default the way Edalize renders it onto a
  /// command line: booleans become `1` / `0`, everything else its
  /// plain string form.
  String _stringifyParamValue(Object? value) {
    if (value is bool) return value ? '1' : '0';
    return value.toString();
  }

  /// Reads `tool_options.verilator`. Returns the `warnFlags` list when
  /// `verilator_options` carried any `-W*` selectors, else `null` so
  /// the engine's own default (`-Wall`) stays in force.
  List<String>? _readVerilatorOptions(
    Object? raw,
    List<String> extraOptions,
    List<String> warnings,
  ) {
    if (raw is! Map) return null;
    List<String>? warnFlags;
    for (final entry in raw.entries) {
      final key = entry.key.toString();
      switch (key) {
        case 'mode':
          // The lint flow sets `mode: lint-only`; LintCrux always
          // invokes Verilator with `--lint-only`, so there is nothing
          // to carry.
          break;
        case 'verilator_options':
          final value = entry.value;
          if (value is! List) break;
          for (final opt in value) {
            if (opt is! String || opt.isEmpty) continue;
            if (opt.startsWith('-W') && opt.length > 2) {
              (warnFlags ??= <String>[]).add(opt.substring(2));
            } else {
              extraOptions.add(opt);
            }
          }
        default:
          warnings.add(
            'tool_options.verilator.$key is not supported; ignored',
          );
      }
    }
    return warnFlags;
  }

  String _resolveAgainst(String baseDir, String path) {
    if (p.isAbsolute(path)) return p.normalize(path);
    return p.normalize(p.join(baseDir, path));
  }
}

/// Aggregate produced by [EdamReader.read].
@immutable
class ImportedEdam {
  /// Creates an [ImportedEdam].
  const ImportedEdam({
    required this.sourceFiles,
    required this.includePaths,
    required this.defines,
    required this.sourceFileLanguages,
    required this.sourceFileProvenance,
    required this.language,
    required this.verilatorExtraOptions,
    required this.verilatorWaiverFiles,
    required this.warnings,
    this.name,
    this.version,
    this.toplevel,
    this.verilatorWarnFlags,
  });

  /// The EDAM `name:` (e.g. `award-winning_serv_serv_1.4.0`), or
  /// `null` when absent.
  final String? name;

  /// The EDAM `version:` string, or `null` when absent. Anything but
  /// [kSupportedEdamVersion] adds a warning.
  final String? version;

  /// The resolved top module, or `null` when the EDAM does not name
  /// one.
  final String? toplevel;

  /// Absolute, normalized HDL source paths in EDAM declaration order.
  final List<String> sourceFiles;

  /// Absolute include directories contributed by `is_include_file`
  /// entries.
  final List<String> includePaths;

  /// Defines from `vlogdefine` parameters that carry a `default`.
  final Map<String, String> defines;

  /// Explicit per-file language, keyed by entries of [sourceFiles] —
  /// EDAM's `file_type` is authoritative, so extension-based detection
  /// never has to guess.
  final Map<String, ProjectSourceFileLanguage> sourceFileLanguages;

  /// Which FuseSoC core (VLNV) contributed each source file, keyed by
  /// entries of [sourceFiles]. Lets downstream surfaces separate "your
  /// code" from "a dependency".
  final Map<String, String> sourceFileProvenance;

  /// Project-level language computed from [sourceFileLanguages].
  final HdlLanguage language;

  /// Verilator `-W*` selectors from `verilator_options` (without the
  /// leading `-W`), or `null` when the EDAM specified none — `null`
  /// keeps the engine's own `-Wall` default in force.
  final List<String>? verilatorWarnFlags;

  /// Non-`-W` entries of `verilator_options`, plus `-G` parameter
  /// overrides synthesized from `vlogparam` defaults.
  final List<String> verilatorExtraOptions;

  /// Absolute paths of `file_type: vlt` Verilator waiver/config files.
  final List<String> verilatorWaiverFiles;

  /// Human-readable reports of everything skipped or approximated.
  /// Never fatal — fatal problems throw [EdamImportException] instead.
  final List<String> warnings;
}

/// Thrown when an EDAM file cannot be imported at all. Carries a
/// human-readable [message] suitable for stderr / a snackbar verbatim.
class EdamImportException implements Exception {
  /// Creates an [EdamImportException] with a human-readable [message].
  const EdamImportException(this.message);

  /// What went wrong, phrased for an end user.
  final String message;

  @override
  String toString() => 'EdamImportException: $message';
}
